name: 'Gabriel Molina '
favicon: null
layout_spectrum: 0.3274859362281859
typography_spectrum: 0.7205243967473507
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.06604290148243308
  lightness: 0.9001347951125354
  saturation: 0.38416070910170674
  rhythmicContrast: 0.5672250562347472
purpose: []
